name: Aikido Security
on:
  push:
    branches: ['**']
  pull_request:

jobs:
  aikido-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run Aikido Scanner
      uses: AikidoSec/github-actions-workflow@v1.0.13
      with:
        secret-key: ${{ secrets.AIKIDO_SECRET_KEY }}
        fail-on-dependency-scan: true
        fail-on-sast-scan: true
        fail-on-iac-scan: true
        minimum-severity: 'HIGH'
        timeout-seconds: 180
