name: CI Pipeline Security Scans

on:
  push:
    branches: ['**']

jobs:
  lint-and-security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 bandit autopep8
        pip install -r requirements.txt

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: Run Linter
      run: flake8 . --max-line-length=100 --exclude=venv,__pycache__,.git || true

    - name: Run bandit scan
      run: bandit -r . -c .bandit.yaml --exclude ./venv,./tests || true

    - name: Run Gitleaks secret scanner
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Run Semgrep SAST scanner
      uses: returntocorp/semgrep-action@v1
      with:
        config: auto

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '0'
