name: CI Pipeline

on:
  push:
    branches: ['**']

jobs:
  lint-and-security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 bandit
        pip install -r requirements.txt
    
    - name: Run flake8
      run: flake8 . --max-line-length=100 --exclude=venv,__pycache__,.git
    
    - name: Run bandit security scan
      run: bandit -r . -f json -o bandit-report.json --exclude ./venv,./tests || true
    
    - name: Display bandit results
      run: bandit -r . --exclude ./venv,./tests
