name: CI Pipeline

on:
  push:
    branches: ['**']

jobs:
  lint-and-security:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autopep8

    - name: Run Formatter
      run: autopep8 -i -r --exclude=venv,__pycache__,.git,.github .

    - name: Run Formatter
      run: autopep8 -i -r --exclude=venv,__pycache__,.git,.github .
    
    - name: Commit formatting changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        git diff --staged --quiet || git commit -m "style: auto-format code with autopep8"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
