name: Linter
on:
  push:
    branches: ['**']
jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install flake8 and plugins
        run: pip install flake8 flake8-bugbear flake8-simplify flake8-bandit
      - name: flake8 Lint with reviewdog
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          flake8_args: "--ignore=F401 --exclude=.git,.github --max-line-length=100"
